baseURL = "https://siansiansu.github.io/"
languageCode = "en-us"
title = "func"
theme = "pickles"

[params]
twitter = "siansiansu"
instagram = "siansian.bird"
github = "siansiansu"
linkedin = "minsian"
author = "Alex Su"
avatar = "/images/avatar.png"
contact = "mailto:minsiansu@gmail.com"
bio = "#Linux, #Vim, #Go, #Python, #Ecologist"
favicon = "/images/favicon.png"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
