name: github pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Static Pages
        run: |
          sudo apt-get install -y hugo
          rm -rf public && hugo -D
          shopt -s extglob
          rm -rf !(.git|public|.gitignore)
          mv ./public/* .

      - name: Push to GitHub Pages
        run: |
        git config --global user.name 'siansiansu'
        git config --global user.email 'minsiansu@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_AUTO_COMMIT }}@github.com/$GITHUB_REPOSITORY
        git checkout -b gh-pages
        git add .
        git commit -m "Automatic publish by GitHub Action"
        git push origin gh-pages -f
