name: github pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Static Pages
        run: |
          sudo apt-get install -y hugo
          rm -rf public && hugo -D
          rm -v !\("public"\)

      - name: Deploy
        run: |
          ls
